apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:   # We dont need to worry about converting to base64
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: go_fullstack_api
  MYSQL_ROOT_PASSWORD: password

  DB_HOST: fullstack-mysql
  DB_DRIVER: mysql
  API_SECRET: db794562156secret7895 
  DB_USER: root
  DB_PASSWORD: password
  DB_NAME: go_fullstack_api
  DB_PORT: "3306"